import { createGlobalTheme } from "@vanilla-extract/css";

export const textTheme = createGlobalTheme(":root", {
  titleH1: {
    fontWeight: "600",
    fontSize: "25px",
    lineHeight: "1.6em",
    letterSpacing: "-0.03em",
    color: "#FFFFFF",
  },
  titleH1Lg: {
    fontWeight: "600",
    fontSize: "30px",
    lineHeight: "1.6em",
    letterSpacing: "-0.03em",
    color: "#FFFFFF",
  },
  titleH2: {
    fontWeight: "600",
    fontSize: "24px",
    lineHeight: "1.6em",
    letterSpacing: "-0.02em",
    color: "#FFFFFF",
  },
  titleH2Lg: {
    fontWeight: "600",
    fontSize: "26px",
    lineHeight: "1.6em",
    letterSpacing: "-0.02em",
    color: "#FFFFFF",
  },
  titleH3: {
    fontWeight: "700",
    fontSize: "20px",
    lineHeight: "1.4em",
    letterSpacing: "-0.02em",
    color: "#FFFFFF",
  },
  titleH3Lg: {
    fontWeight: "700",
    fontSize: "22px",
    lineHeight: "1.6em",
    letterSpacing: "-0.02em",
    color: "#FFFFFF",
  },
  bodyB1: {
    fontWeight: "500",
    fontSize: "17px",
    lineHeight: "1.8em",
    letterSpacing: "-0.02em",
    color: "#FFFFFF",
  },
  bodyB1Lg: {
    fontWeight: "500",
    fontSize: "18px",
    lineHeight: "1.8em",
    letterSpacing: "-0.02em",
    color: "#FFFFFF",
  },
  bodyB2: {
    fontWeight: "500",
    fontSize: "15px",
    lineHeight: "1.5em",
    letterSpacing: "-0.02em",
    fontStyle: "italic",
    color: "#FFFFFF",
  },
  bodyB2Lg: {
    fontWeight: "500",
    fontSize: "15px",
    lineHeight: "1.6em",
    letterSpacing: "-0.02em",
    fontStyle: "italic",
    color: "#FFFFFF",
  },
  caption16: {
    fontWeight: "500",
    fontSize: "16px",
    lineHeight: "1.6em",
    letterSpacing: "-0.02em",
    color: "#666",
  },
  caption15: {
    fontWeight: "500",
    fontSize: "15px",
    lineHeight: "1.6em",
    letterSpacing: "-0.02em",
    color: "#FFFFFF",
  },
  caption14: {
    fontWeight: "500",
    fontSize: "14px",
    lineHeight: "1.6em",
    letterSpacing: "-0.02em",
    color: "#FFFFFF",
  },
});
