import Providers from "@/app/providers";
import { pretendard } from "@/shared/styles/base/font";
import type { Metadata } from "next";
import type { ReactNode } from "react";

import "@/shared/styles/base/global.css";
import "@/shared/styles/base/reset.css";
import { rootStyle } from "@/shared/styles/base/global.css";

import SprinkleContainer from "@/shared/ui/sprinkle-container";

// TODO: 추후 수정
export const metadata: Metadata = {
  title: "Lettie",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="ko" className={pretendard.className}>
      <body className={rootStyle}>
        <Providers>{children}</Providers>
        <SprinkleContainer />
      </body>
    </html>
  );
}
