import Providers from "@/app/providers";
import { pretendard } from "@/shared/styles/base/font";
import type { Metadata } from "next";
import type { ReactNode } from "react";

// TODO: 추후 수정

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="ko" className={pretendard.className}>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
